export const BASE_URL = 'https://manage-service-api-demo.herokuapp.com/api'
// export const DEPARTMENT_URL = BASE_LOCAL_URL || BASE_URL + 'department'
export const DEPARTMENT_URL = BASE_URL + '/department'
export const STAFF_URL = BASE_URL + '/staff'
export const NEWS_URL = BASE_URL + '/news'
export const SENDER_URL = BASE_URL + '/sender'
export const FIELD_URL = BASE_URL + '/field'
export const UNIT_URL = BASE_URL + '/unit'
export const SERVICE_URL = BASE_URL + '/service'
export const PROFILE_URL = BASE_URL + '/profile'

export const CLOUD_URI = 'https://api.cloudinary.com/v1_1/duytrann/image/upload'
export const PRESENT = 'ml_default'
